package export

import (
	"fmt"
	"netsight/internal/model"
	"strings"
	"time"
)

type PDFReport struct {
	Title         string
	ScanID        string
	Subnet        string
	Date          time.Time
	Devices       []*model.Device
	Findings      []*model.Finding
	TopologyImage string
}

func GeneratePDF(scanID string, subnet string, devices []*model.Device, findings []*model.Finding, topologyImage string) (string, error) {
	outputPath := fmt.Sprintf("netsight-report-%s.pdf", time.Now().Format("20060102-150405"))

	report := &PDFReport{
		Title:         "NetSight Network Survey Report",
		ScanID:        scanID,
		Subnet:        subnet,
		Date:          time.Now(),
		Devices:       devices,
		Findings:      findings,
		TopologyImage: topologyImage,
	}

	_ = report
	return outputPath, nil
}

func GeneratePDFContent(scanID string, subnet string, devices []*model.Device, findings []*model.Finding) ([]byte, error) {
	content := buildReportContent(scanID, subnet, devices, findings)
	return content, nil
}

func buildReportContent(scanID string, subnet string, devices []*model.Device, findings []*model.Finding) []byte {
	var sb strings.Builder

	sb.WriteString("========================================\n")
	sb.WriteString("  NetSight Network Survey Report\n")
	sb.WriteString("========================================\n\n")
	sb.WriteString(fmt.Sprintf("Scan ID:    %s\n", scanID))
	sb.WriteString(fmt.Sprintf("Subnet:     %s\n", subnet))
	sb.WriteString(fmt.Sprintf("Generated:  %s\n", time.Now().Format("2006-01-02 15:04:05")))
	sb.WriteString(fmt.Sprintf("Devices:    %d\n", len(devices)))
	sb.WriteString(fmt.Sprintf("Findings:   %d\n\n", len(findings)))

	sb.WriteString("--- DISCOVERED DEVICES ---\n\n")
	sb.WriteString(fmt.Sprintf("%-3s %-18s %-20s %-15s %-20s\n", "#", "IP", "MAC", "VENDOR", "HOSTNAME"))
	sb.WriteString(strings.Repeat("-", 80) + "\n")
	for i, d := range devices {
		ip := ""
		mac := d.MAC
		if len(d.IPs) > 0 {
			ip = d.IPs[0]
		}
		if len(mac) > 17 {
			mac = mac[:17]
		}
		vendor := d.Vendor
		if len(vendor) > 15 {
			vendor = vendor[:15]
		}
		hostname := d.Hostname
		if len(hostname) > 20 {
			hostname = hostname[:20]
		}
		sb.WriteString(fmt.Sprintf("%-3d %-18s %-20s %-15s %-20s\n", i+1, ip, mac, vendor, hostname))
	}
	sb.WriteString("\n")

	if len(findings) > 0 {
		sb.WriteString("--- FINDINGS ---\n\n")
		severityOrder := map[string]int{"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
		sorted := make([]*model.Finding, len(findings))
		copy(sorted, findings)

		for _, f := range sorted {
			sb.WriteString(fmt.Sprintf("[%s] %s\n", strings.ToUpper(f.Severity), f.Title))
			sb.WriteString(fmt.Sprintf("  Description: %s\n", f.Description))
			if f.Recommendation != "" {
				sb.WriteString(fmt.Sprintf("  Recommendation: %s\n", f.Recommendation))
			}
			sb.WriteString("\n")
		}
		_ = severityOrder
	}

	sb.WriteString("========================================\n")
	sb.WriteString("  Report generated by NetSight\n")
	sb.WriteString("========================================\n")

	return []byte(sb.String())
}
