package export

import (
	"fmt"
	"netsight/internal/model"
	"os"
	"strings"
	"time"
)

type PDFReport struct {
	Title         string
	ScanID        string
	Subnet        string
	Date          time.Time
	Devices       []*model.Device
	Findings      []*model.Finding
	TopologyImage string
}

func GeneratePDF(scanID string, subnet string, devices []*model.Device, findings []*model.Finding, topologyImage string) (string, error) {
	outputPath := fmt.Sprintf("netsight-report-%s.pdf", time.Now().Format("20060102-150405"))

	report := &PDFReport{
		Title:         "NetSight Network Survey Report",
		ScanID:        scanID,
		Subnet:        subnet,
		Date:          time.Now(),
		Devices:       devices,
		Findings:      findings,
		TopologyImage: topologyImage,
	}

	content := buildPDF(scanID, subnet, devices, findings)
	if err := os.WriteFile(outputPath, content, 0644); err != nil {
		return "", fmt.Errorf("failed to write PDF report: %w", err)
	}

	_ = report
	return outputPath, nil
}

func GeneratePDFContent(scanID string, subnet string, devices []*model.Device, findings []*model.Finding) ([]byte, error) {
	content := buildPDF(scanID, subnet, devices, findings)
	return content, nil
}

func buildPDF(scanID, subnet string, devices []*model.Device, findings []*model.Finding) []byte {
	text := buildReportContent(scanID, subnet, devices, findings)
	lines := strings.Split(string(text), "\n")
	stream := "BT\n/F1 9 Tf\n40 770 Td\n"
	for _, line := range lines {
		line = strings.ReplaceAll(strings.ReplaceAll(line, `\`, `\\`), "(", `\(`)
		line = strings.ReplaceAll(line, ")", `\)`)
		stream += "(" + line + ") Tj 0 -12 Td\n"
	}
	stream += "ET\n"
	objects := []string{"<< /Type /Catalog /Pages 2 0 R >>", "<< /Type /Pages /Kids [3 0 R] /Count 1 >>", "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>", "<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>", fmt.Sprintf("<< /Length %d >>\nstream\n%sendstream", len(stream), stream)}
	var out strings.Builder
	out.WriteString("%PDF-1.4\n")
	offsets := []int{0}
	for i, obj := range objects {
		offsets = append(offsets, out.Len())
		fmt.Fprintf(&out, "%d 0 obj\n%s\nendobj\n", i+1, obj)
	}
	xref := out.Len()
	fmt.Fprintf(&out, "xref\n0 %d\n0000000000 65535 f \n", len(objects)+1)
	for _, offset := range offsets[1:] {
		fmt.Fprintf(&out, "%010d 00000 n \n", offset)
	}
	fmt.Fprintf(&out, "trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n", len(objects)+1, xref)
	return []byte(out.String())
}

func buildReportContent(scanID string, subnet string, devices []*model.Device, findings []*model.Finding) []byte {
	var sb strings.Builder

	sb.WriteString("========================================\n")
	sb.WriteString("  NetSight Network Survey Report\n")
	sb.WriteString("========================================\n\n")
	sb.WriteString(fmt.Sprintf("Scan ID:    %s\n", scanID))
	sb.WriteString(fmt.Sprintf("Subnet:     %s\n", subnet))
	sb.WriteString(fmt.Sprintf("Generated:  %s\n", time.Now().Format("2006-01-02 15:04:05")))
	sb.WriteString(fmt.Sprintf("Devices:    %d\n", len(devices)))
	sb.WriteString(fmt.Sprintf("Findings:   %d\n\n", len(findings)))

	sb.WriteString("--- DISCOVERED DEVICES ---\n\n")
	sb.WriteString(fmt.Sprintf("%-3s %-18s %-20s %-15s %-20s\n", "#", "IP", "MAC", "VENDOR", "HOSTNAME"))
	sb.WriteString(strings.Repeat("-", 80) + "\n")
	for i, d := range devices {
		ip := ""
		mac := d.MAC
		if len(d.IPs) > 0 {
			ip = d.IPs[0]
		}
		if len(mac) > 17 {
			mac = mac[:17]
		}
		vendor := d.Vendor
		if len(vendor) > 15 {
			vendor = vendor[:15]
		}
		hostname := d.Hostname
		if len(hostname) > 20 {
			hostname = hostname[:20]
		}
		sb.WriteString(fmt.Sprintf("%-3d %-18s %-20s %-15s %-20s\n", i+1, ip, mac, vendor, hostname))
	}
	sb.WriteString("\n")

	if len(findings) > 0 {
		sb.WriteString("--- FINDINGS ---\n\n")
		severityOrder := map[string]int{"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
		sorted := make([]*model.Finding, len(findings))
		copy(sorted, findings)

		for _, f := range sorted {
			sb.WriteString(fmt.Sprintf("[%s] %s\n", strings.ToUpper(f.Severity), f.Title))
			sb.WriteString(fmt.Sprintf("  Description: %s\n", f.Description))
			if f.Recommendation != "" {
				sb.WriteString(fmt.Sprintf("  Recommendation: %s\n", f.Recommendation))
			}
			sb.WriteString("\n")
		}
		_ = severityOrder
	}

	sb.WriteString("========================================\n")
	sb.WriteString("  Report generated by NetSight\n")
	sb.WriteString("========================================\n")

	return []byte(sb.String())
}
